### ISSUE TITLE
Scoring for spanish deck

### ISSUE THREAD

**Issue by wilsalex** [cs361fall2017/team28#35]

**Comment by okubod** [comment]
What exactly is needed for this? I changed up the check_end function to check the score based on whether it is a standard or Spanish game to account for the extra cards. We don't need to keep a separate counter for the scoring of a Spanish game do we?

**Comment by wilsalex** [comment]
I think that's all that is needed. Score for a win with the Spanish deck should be 46 instead of the normal 48.
